---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: blue-niri
# description will be included in the image's metadata
description: I like Niri. This only exists until wayblue makes their own.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - from-file: niri-modules.yml
  - from-file: extra-packages-recipes.yml
  - from-file: blue-modules.yml
  - from-file: multimedia-modules.yml
  - from-file: extra-non-niri-recipes.yml
  
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
